#!/usr/bin/env python3
#	pygdb - Python GDB convenience frontend
#	Copyright (C) 2020-2020 Johannes Bauer
#
#	This file is part of pygdb.
#
#	pygdb is free software; you can redistribute it and/or modify
#	it under the terms of the GNU General Public License as published by
#	the Free Software Foundation; this program is ONLY licensed under
#	version 3 of the License, later versions are explicitly excluded.
#
#	pygdb is distributed in the hope that it will be useful,
#	but WITHOUT ANY WARRANTY; without even the implied warranty of
#	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#	GNU General Public License for more details.
#
#	You should have received a copy of the GNU General Public License
#	along with pygdb; if not, write to the Free Software
#	Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#
#	Johannes Bauer <JohannesBauer@gmx.de>

from Tools import Tools

assert(Tools.to_int("123") == 123)
assert(Tools.to_int("123k") == 123 * 1024)
assert(Tools.to_int("123 M") == 123 * 1024 * 1024)
assert(Tools.to_int("0x123 M") == 0x123 * 1024 * 1024)

assert(Tools.parse_args("") == [ ])
assert(Tools.parse_args("foo") == [ "foo" ])
assert(Tools.parse_args("foo bar moo") == [ "foo", "bar", "moo" ])
assert(Tools.parse_args("foo \"bar moo\"") == [ "foo", "bar moo" ])
assert(Tools.parse_args("foo \"bar\\\" moo\"") == [ "foo", "bar\" moo" ])
assert(Tools.parse_args("foo \"bar\\\" moo\" koo") == [ "foo", "bar\" moo", "koo" ])
